config/routes.rb
Rails.application.routes.draw do

  resources :bookmarks

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions
  resources :users

  post :incoming, to: 'incoming#create'
  

  root 'pages#home'

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_uniqueness_of :email
  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # vvvvvv parkerhill standard  vvvvvv

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end

  include Pundit
  # after_action :verify_authorized, :except => :index
  # after_action :verify_policy_scoped, :only => :index
  rescue_from Pundit::NotAuthorizedError do |exception|
    redirect_to root_url, alert: exception.message
  end

  # http://railscasts.com/episodes/131-going-back
  def back_path
    request.referrer || root_path
  end

  # e.g. before_action :save_back, only: [:new, :edit]
  def save_back
    session[:last_page] = back_path
  end

  # eg link_to 'Continue from before', saved_back_path if saved_back_path
  def saved_back_path
    session[:last_page]
  end
  helper_method :back_path, :save_back, :saved_back_path

  # config/application.rb
  def app_title
    Rails.application.config.app_title
  end
  helper_method :app_title

  # vvvvvv app specific vvvvvv

  private
  # vvvvvv parkerhill standard vvvvvv

  def user_not_authorized
    flash[:error] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end


  # vvvvvv app specific vvvvvv
  
  def current_user
    @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  expose(:bookmarks)
  expose(:bookmark, attributes: :bookmark_params)

  def create
    return redirect_to(login_path) unless current_user

    bookmark.user = current_user
    if bookmark.save
      redirect_to bookmarks_path, notice: 'Bookmark saved'
    else
      render :new
    end
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:link, :topic)
  end
end

app/controllers/incomming_controller.rb
require "uri"

class IncomingController < ApplicationController

  # http://stackoverflow.com/questions/1177863/how-do-i-ignore-the-authenticity-token-for-specific-actions-in-rails
  skip_before_filter :verify_authenticity_token, only: [:create]

  def create
    # Take a look at these in your server logs
    # to get a sense of what you're dealing with.
    logger.info "INCOMING PARAMS HERE: #{params}"
    logger.info "keys: #{params.keys}"
    logger.info "stripped-text: #{params['stripped-text']}"

    email = params[:sender] 
    user = User.find_by_email email
    topic = /#(\w*)/.match(params[:subject])[1] # e.g "foo #tag bar"
    # http://stackoverflow.com/questions/3665072/extract-url-from-text
    link  =  URI.extract(params['stripped-text'], /http(s)?/).first


    if user
      ok = user.bookmarks.create topic: topic, link: link
      if ok
        logger.info "Created bookmark: #{topic}: #{link}"
      else
        logger.info "failed to create bookmark: #{topic}: #{link}"
      end
      
    else
      logger.info "unknown user #{email}"
    end

    # Assuming all went well. 
    head 200
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  expose(:user, attributes: :user_params)

  def create
    if user.save
      session[:user_id] = user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  # vvvvvv parkerhill standard  vvvvvv

  def config(setting)
    Rails.application.config.send setting
  end

  def title(page_title, show: true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show
  end

  def show_title?
    @show_title
  end

  def flash_class_for(level)
    'alert alert-dismissable ' +
      case level
      when 'success' then 'alert-success' # green
      when 'notice'  then 'alert-info'    # blue
      when 'alert'   then 'alert-warning' # yellow
      when 'error'   then 'alert-warning' # yellow ('alert-danger' - red)
      else                'alert-info'    # blue
      end
  end

  # vvvvvv app specific vvvvvv

end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookmarks/index.html.haml
%h1 Bookmarks

%table.table
  - bookmarks.each do |bookmark|
    %tr
      %td= bookmark.link
      %td= bookmark.topic
      %td= bookmark.user.email

%p
  = link_to 'Add', new_bookmark_path, class: 'btn btn-primary'

app/views/bookmarks/new.html.haml
%h1 Add Bookmark

= simple_form_for bookmark do |f|
  = f.input :link
  = f.input :topic

  = f.submit

app/views/layouts/_flash.html.haml
- flash.each do |level, msg|
  = content_tag :div, class: flash_class_for(level) do
    %button.close{ type: :button, data_dismiss: :alert, aria_hidden: true } &times;
    = raw msg

app/views/layouts/_footer.html.haml
#footer
  .small.align_right Copyright &copy; #{Time.now.year} #{config :copyright}

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top{ role: :navigation }
  .container-fluid
    / mobile 
    .navbar-header
      %button.navbar-toggle{ type: :button, data: { toggle: :collapse, target: '#navbar-collapse' } }
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{ href: '/' }= app_title
  
    #navbar-collapse.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li= link_to 'Bookmarks', bookmarks_path

      %ul.nav.navbar-nav.navbar-right
        - if current_user
          %li= link_to "Logged in as #{ current_user.email }", '#'
          %li= link_to 'Log out', logout_path
        - else
          %li= link_to 'Sign up', signup_path
          %li= link_to 'Sign in', login_path
      /   - if current_user
      /     %li= link_to current_user.name, profile_path
      /     %li= link_to 'Sign out', signout_path, id: 'sign_out'
      /   - else
      /     %li= link_to 'Sign in via Facebook', '/auth/facebook', id: 'sign_in'

      / %ul.nav.navbar-nav.navbar-right
      /   - if current_user
      /     %li= link_to 'Account', account_path
      /     %li= link_to 'Profile', edit_user_registration_path
      /     %li= link_to 'Sign out', destroy_user_session_path, method: :delete
      /   - else
      /     %li= link_to 'Sign in', new_user_session_path

app/views/layouts/application.html.haml
-# vvvvvv parkerhill standard  vvvvvv -
-# keep this generic, no application specific code -
!!!
%html
  %head
    %title= [app_title, yield(:title)].join(' | ')
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1' }
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = yield(:head)
  %body{ data: { controller: "#{controller_name}", action: "#{action_name}" }}
    .container
      = render 'layouts/navbar'
    #banner
    .container
      #content
        = render 'layouts/flash'
        - if show_title?
          %h1= yield(:title)
        = content_for?(:content) ? yield(:content) : yield
      = render 'layouts/footer'

app/views/pages/home.html.haml
%h1 Home
%p Welcome to #{Rails.application.config.app_title}
%p
  %span.glyphicon.glyphicon-ok

app/views/users/new.html.haml
%h1 Sign up
= simple_form_for user do |f|
  .error_messages
    %h2 Form is invalid
    %ul
      - user.errors.full_messages.each do |message|
        %li= message

  = f.input :email
  = f.input :password
  = f.input :password_confirmation
  = f.submit 'Sign Up', class: 'btn btn-primary'